### ISSUE TITLE
Add documentation about cssDest Param.

### ISSUE THREAD

**Issue by ethyde** [Exictos-DCS/dcs-icon-font#2]
Hi,

this param are usefull, but there is no doc about it.

**Comment by OrencioRodolfo** [comment]
@ethyde, you're right.

Both *cssDest* and *cssFontsUrl* are missing from the documentation.
Will fix it soon.

Thank you

**Comment by OrencioRodolfo** [comment]
Closed by commit 90d304debe7a24fcc5dcf49a7bea5a1fc30620da (Missing "Closes #1" on commit message)
