### ISSUE TITLE
How to use custom template ?

### ISSUE THREAD

**Issue by ethyde** [Exictos-DCS/dcs-icon-font#3]
I need to customise some part of the css template, how to do that ?

Thx.

**Comment by OrencioRodolfo** [comment]
@ethyde, 

At this moment it is no possible via CLI args.
For that you would have to clone the project and define your own template in the **templates** folder.

However, it is perfectly possible to add this argument to the CLI.
Will try to do it ASAP.

**Comment by OrencioRodolfo** [comment]
@ethyde, 

Now, with the new release 2.2.0 you can specify a custom HTML template. Check the documentation for more details.

**Comment by ethyde** [comment]
Yeah, thank you so much ! :)
