### ISSUE TITLE
How to use options like "fixedWidth, centerHorizontally, normalize" etc. ?

### ISSUE THREAD

**Issue by ethyde** [Exictos-DCS/dcs-icon-font#4]
Hi !

I need to custom some font option like "fixedWidth, centerHorizontally, normalize" who are available in webfont generator : https://github.com/sunflowerdeath/webfonts-generator#fontname-fixedwidth-centerhorizontally-normalize-fontheight-round-descent.

So how to achieve that ? :)

Thanks by advance !

**Comment by OrencioRodolfo** [comment]
Hi @ethyde,

The specified options are now supported.
Please check the [changelog](https://github.com/Exictos-DCS/dcs-icon-font/blob/master/CHANGELOG.md#v221-06-11-2016) file.

Thanks!
