### ISSUE TITLE
Error when source folder is empty

### ISSUE THREAD

**Issue by ethyde** [Exictos-DCS/dcs-icon-font#5]
Hi !

I have this error : 
![capture d ecran 2017-01-12 a 17 49 00](https://cloud.githubusercontent.com/assets/409987/21899395/50cc442e-d8f0-11e6-8abc-338eb4ac7638.png)

I know it's not occur very often but, can you add a test to skip build when source folder is empty ?

I think it could be very usefull to have better error message than "Fatal error: Invalid file list" , in this case. And, why not, for other params who need path to folder/file.

**Comment by OrencioRodolfo** [comment]
Hi @ethyde, sorry for the late answer.

I'm not getting what you mean. When the you give an empty file list, an error is thrown because the build cannot succeed when no SVGs are provided.

[dcs-icon-font/src/builder.js](https://github.com/Exictos-DCS/dcs-icon-font/blob/master/src/builder.js)

```javascript
if (!files.length) {
   reject(new Error('Invalid file list'));
}
```

**Comment by ethyde** [comment]
Hi @OrencioRodolfo thanks for your answer.

Oh ok, so I think the message was not very accurate to understand the problem, something like "No valid file detected" would be better ?

And some of my co-worker, who are not familliar with node JS error, are worried about the error log after message... It's possible to pipe it ?

**Comment by OrencioRodolfo** [comment]
@ethyde, already published a new version on NPM with a more specific error message. See cc3db6cfcfa715ee51a489877c3e2f60c031003f.

I hope is enough. If not, please make a Pull Request with the pretended changes

**Comment by ethyde** [comment]
Perfect ! :)
