### ISSUE TITLE
Update webfonts-generator version to 0.4.0

### ISSUE THREAD

**Issue by Didou518** [Exictos-DCS/dcs-icon-font#6]
Can you update webfonts-generator to version 0.4.0 ?
With this update we can generate woff2 fonts.

Thank you !!!

 https://github.com/sunflowerdeath/webfonts-generator/commit/fc41106106ee35408314159d18dc31c71dab3bfd

**Comment by RodolfoGoncalves** [comment]
Hi,

Just release version 3.0.0 supporting webfonts-generator@0.4.0

Please, check the changelog uptdates
https://github.com/Exictos-DCS/dcs-icon-font/blob/master/CHANGELOG.md#v300-08-03-2017
